//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

//------------------------------------------------------------------------------

namespace VUS.Course.Shared
{
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum vus_TimeOptions
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("09:00 AM", 0)]
		_0900AM = 953640000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("09:30 AM", 1)]
		_0930AM = 953640001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("10:00 AM", 2)]
		_1000AM = 953640002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("10:30 AM", 3)]
		_1030AM = 953640003,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("11:00 AM", 4)]
		_1100AM = 953640004,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("11:30 AM", 5)]
		_1130AM = 953640005,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("12:00 PM", 6)]
		_1200PM = 953640006,
	}
}